version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm          
      - run:
          command: npm run build 
          name: Build app reactjs
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_on_commit:
    jobs:
      - build_and_test
